import "three/examples/js/loaders/OBJLoader";
import "three/examples/js/loaders/RGBELoader";
import "three/examples/js/loaders/GLTFLoader";
import "three/examples/js/loaders/DRACOLoader";
import "three/examples/js/loaders/FBXLoader";
// import "three/examples/js/loaders/EquirectangularToCubeGenerator";
import "three/examples/js/loaders/STLLoader";
import "three/examples/js/loaders/STLLoader";
import "three/examples/js/loaders/MTLLoader";
import "three/examples/js/controls/OrbitControls";
import "three/examples/js/controls/FirstPersonControls";
import "three/examples/js/controls/FirstPersonControls";
import "three/examples/js/controls/FlyControls";
import "three/examples/js/shaders/CopyShader.js";
import "three/examples/js/shaders/BokehShader.js";
import "three/examples/js/shaders/SSAOShader.js";
import "three/examples/js/shaders/LuminosityHighPassShader.js";
import "three/examples/js/shaders/SMAAShader.js";
import "three/examples/js/shaders/ConvolutionShader.js";
import "three/examples/js/shaders/FXAAShader.js";
import "three/examples/js/shaders/DepthLimitedBlurShader.js";
import "three/examples/js/shaders/SAOShader.js";
import "three/examples/js/shaders/UnpackDepthRGBAShader.js";
import "three/examples/js/postprocessing/EffectComposer.js";
import "three/examples/js/postprocessing/BokehPass.js";
import "three/examples/js/postprocessing/ShaderPass.js";
import "three/examples/js/postprocessing/RenderPass.js";
import "three/examples/js/postprocessing/SSAOPass.js";
import "three/examples/js/postprocessing/SAOPass.js";
import "three/examples/js/postprocessing/SMAAPass.js";
import "three/examples/js/postprocessing/BloomPass.js";
import "three/examples/js/postprocessing/UnrealBloomPass.js";



import "three/examples/js/postprocessing/EffectComposer";
import "three/examples/js/shaders/CopyShader";
import "three/examples/js/shaders/LuminosityHighPassShader";
import "three/examples/js/shaders/ColorCorrectionShader";
import "three/examples/js/shaders/UnpackDepthRGBAShader";
import "three/examples/js/shaders/DepthLimitedBlurShader";
import "three/examples/js/shaders/SAOShader";
import "three/examples/js/shaders/FilmShader";
import "three/examples/js/shaders/FXAAShader";
import "three/examples/js/shaders/SMAAShader";
import "three/examples/js/shaders/SSAOShader";
import "three/examples/js/shaders/RGBShiftShader";
import "three/examples/js/shaders/VerticalTiltShiftShader";
import "three/examples/js/shaders/HorizontalTiltShiftShader";
import "three/examples/js/postprocessing/SavePass";
import "three/examples/js/postprocessing/ShaderPass";
import "three/examples/js/postprocessing/MaskPass";
import "three/examples/js/postprocessing/RenderPass";
import "three/examples/js/postprocessing/SMAAPass";
import "three/examples/js/postprocessing/FilmPass";
import "three/examples/js/postprocessing/SSAOPass";
import "three/examples/js/postprocessing/SAOPass";
import "three/examples/js/postprocessing/ClearPass";
import "three/examples/js/postprocessing/UnrealBloomPass";


import "three/examples/js/loaders/HDRCubeTextureLoader";
import "three/examples/js/pmrem/PMREMGenerator";
import "three/examples/js/pmrem/PMREMCubeUVPacker";
